spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

server:
  forward-headers-strategy: framework

logging:
  level:
    org:
      hibernate: info
      springframework: debug